[tool.ruff]
target-version = "py310"
select = [
    "B",
    "C",
    "COM",
    "E",
    "F",
    "I",
    "UP",
]
ignore = [
    "C901", # Complexity
    "E501", # Line length
]
unfixable = [
    "B007", # Loop control variable not used within the loop body
]
